-- Keep the storefront catalog aligned with the actual Excel workbooks generated by
-- app/api/products/download/route.ts. Remove claims for features that are not
-- present in the purchased files and remove unsupported popularity badges.

UPDATE `Product`
SET
  `description` = 'Practical event budget workbook with 55 editable expense rows, budget-versus-actual variance formulas, vendor/payment fields and totals.',
  `features` = JSON_ARRAY(
    '55 editable budget and expense rows across common event categories',
    'Budget, actual and automatic variance formulas',
    'Vendor, payment status and notes fields',
    'Currency shown from the purchased order and a purchase/license sheet'
  ),
  `badge` = NULL,
  `fileDownloadKey` = 'ultimate-event-budget-planner.xlsx'
WHERE `slug` = 'ultimate-event-budget-planner';

UPDATE `Product`
SET
  `description` = 'Wedding budget workbook with editable couple/event details, 90 expense rows, due dates, vendor contacts, payment status and automatic budget-versus-actual variance.',
  `features` = JSON_ARRAY(
    '90 editable wedding expense rows across 17 common categories',
    'Wedding or couple name, event date, guest count and currency fields',
    'Budget, actual and automatic variance formulas',
    'Due date, vendor/contact and payment status fields'
  ),
  `badge` = NULL,
  `fileDownloadKey` = 'wedding-budget-planner.xlsx'
WHERE `slug` = 'wedding-budget-planner';

UPDATE `Product`
SET
  `description` = 'Corporate event workbook with stakeholder planning, a vendor RFP comparison matrix and a sponsorship revenue calculator, all built from blank user-entry fields.',
  `features` = JSON_ARRAY(
    'Stakeholder and deliverable planner with 35 editable rows',
    'Vendor RFP comparison matrix with 25 editable rows',
    'Sponsorship calculator with 12 tier rows and revenue formulas',
    'Event name, date, objective, target attendance and budget fields'
  ),
  `badge` = NULL,
  `fileDownloadKey` = 'corporate-event-planner.xlsx'
WHERE `slug` = 'corporate-event-planner';

UPDATE `Product`
SET
  `description` = 'Conference workbook covering agenda and stage flow, speaker management, and sponsor/exhibitor tracking with blank fields ready for your event data.',
  `features` = JSON_ARRAY(
    'Conference agenda and stage-flow sheet with 100 editable rows',
    'Speaker management sheet with 50 editable rows',
    'Sponsor and exhibitor tracker with 50 editable rows',
    'Session, room, AV cue, contact, travel and payment-status fields'
  ),
  `badge` = NULL,
  `fileDownloadKey` = 'conference-planner.xlsx'
WHERE `slug` = 'conference-planner';

UPDATE `Product`
SET
  `description` = 'Event ticket-yield workbook for entering ticket tiers, expected sales and processor/platform fees, with automatic gross sales, net sales, profit and break-even calculations.',
  `features` = JSON_ARRAY(
    '15 editable ticket-tier rows',
    'Gross sales and net sales formulas',
    'Processor/platform fee input fields',
    'Estimated profit and break-even ticket calculations'
  ),
  `badge` = NULL,
  `fileDownloadKey` = 'event-profit-planner.xlsx'
WHERE `slug` = 'event-profit-planner';

UPDATE `Product`
SET
  `description` = 'Event ROI workbook for entering investment, direct revenue, pipeline value, other measurable returns and qualified leads, with automatic ROI and cost-per-lead calculations.',
  `features` = JSON_ARRAY(
    'Event investment and measurable return inputs',
    'Direct revenue, pipeline/opportunity and other-return fields',
    'Automatic total return, net return and ROI calculations',
    'Qualified lead input and cost-per-qualified-lead calculation'
  ),
  `badge` = NULL,
  `fileDownloadKey` = 'event-roi-planner.xlsx'
WHERE `slug` = 'event-roi-planner';

UPDATE `Product`
SET
  `description` = 'Editable event planning checklist with 320 rows across nine planning phases, including ownership, due dates, priority, status and notes.',
  `features` = JSON_ARRAY(
    '320 editable checklist rows',
    'Nine planning phases from strategy through post-event work',
    'Owner, due date, priority, status and notes fields',
    'Filterable worksheet with a default Not started status for new tasks'
  ),
  `badge` = NULL,
  `fileDownloadKey` = 'event-planning-checklist.xlsx'
WHERE `slug` = 'event-planning-checklist';

UPDATE `Product`
SET
  `description` = 'Complete workbook bundle containing the seven standalone Toolbox.Events planners in one Excel file, with each workbook section using blank user-entry fields and formulas.',
  `features` = JSON_ARRAY(
    'Includes the seven standalone Toolbox.Events planner workbooks as worksheet groups',
    'Budget, wedding, corporate, conference, profit, ROI and checklist worksheets',
    'Blank user-entry fields with formulas instead of fabricated event data',
    'One-time purchase with a bundle price of about 61% below the combined standalone prices'
  ),
  `badge` = 'Best Value',
  `fileDownloadKey` = 'complete-event-planning-bundle.xlsx'
WHERE `slug` = 'complete-event-planning-bundle';
